// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDQ-UETB03fLb52hdDToOWbhihWlYopMU',
    appId: '1:499783588915:web:5b6662f586c1d3b98a5746',
    messagingSenderId: '499783588915',
    projectId: 'infomat-39565',
    authDomain: 'infomat-39565.firebaseapp.com',
    storageBucket: 'infomat-39565.appspot.com',
    measurementId: 'G-8EGPGEJZEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH3jBFWKJd3sdoMFb0_gN75iy_SHTsLtY',
    appId: '1:499783588915:android:d9cbd3f407dc40a78a5746',
    messagingSenderId: '499783588915',
    projectId: 'infomat-39565',
    storageBucket: 'infomat-39565.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1nrz0Kj67NFGqtdvVSuf-kBRxZOKenLw',
    appId: '1:499783588915:ios:a0da9692fd9b09aa8a5746',
    messagingSenderId: '499783588915',
    projectId: 'infomat-39565',
    storageBucket: 'infomat-39565.appspot.com',
    iosBundleId: 'com.example.infomat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1nrz0Kj67NFGqtdvVSuf-kBRxZOKenLw',
    appId: '1:499783588915:ios:df00a9987a03a06d8a5746',
    messagingSenderId: '499783588915',
    projectId: 'infomat-39565',
    storageBucket: 'infomat-39565.appspot.com',
    iosBundleId: 'com.example.infomat.RunnerTests',
  );
}
